### ISSUE TITLE
All coursework assignments migrated to Github issues

### ISSUE THREAD

**Issue by Dedekind561** [CodeYourFuture/Tech-Ed-Next#9]
- [ ] All G Classroom tech ed assignments are transferred to Github issues
- [ ] All new issues have correct labels according to their type e.g. mandatory, etc
- [ ] All Github issues are exposed on a Github project board as cards
- [ ] All Github cards are labelled according to their week in the module
- [ ] Each project board has a **Backlog**, **By priority**, **By Week**, **Done** view

## TODO
- [x] Fundamentals
- [x] HTML-CSS
- [x] JS1
- [ ] JS2
- [x] JS3
- [x] Node
- [x] Databases

**Comment by SallyMcGrath** [comment]
# HTML first pass done:

https://github.com/CodeYourFuture/Module-HTML-CSS 
https://github.com/orgs/CodeYourFuture/projects/87/views/4

- [x] All G Classroom tech ed assignments are transferred to Github issues
- [x] All new issues have correct labels according to their type e.g. mandatory, etc
- [x] All Github issues are exposed on a Github project board as cards
- [x] All Github cards are labelled according to their week in the module *note on this
- [x] Each project board has a **Backlog**, **By priority**, **By Week**, **Done** view

Also moved the mandatory projects into the repo
Rewrote step by step tutorials as project briefings
Moved the solutions into a branch
Deployed the repo to Netlify so disposable branch previews will activate automatically on PR

NOT DONE
automatic labelling by field (blocker: access token permissions on org)
PD isn't in, as that's not my job

**Comment by SallyMcGrath** [comment]
## Databases first pass done
https://github.com/CodeYourFuture/Module-Databases
https://github.com/orgs/CodeYourFuture/projects/89/views/2 

- [x] All G Classroom tech ed assignments are transferred to Github issues
- [x] All new issues have correct labels according to their type e.g. mandatory, etc
- [x] All Github issues are exposed on a Github project board as cards
- [x] All Github cards are labelled according to their week in the module
- [x] Each project board has a **Backlog**, **By priority**, **By Week**, **Done** view

Also moved the mandatory projects into the repo
Rewrote step by step tutorials as project briefings
Rewrote e-commerce api as a dialogue with colleagues
Rewrote API task as a TDD project with starter test and acceptance criteria
Designed feature branch subtask to prep for final projects

## NOT DONE
automatic labelling by field (blocker: access token permissions on org)
PD isn't in, as that's not my job
solutions are not in a branch because I haven't written any yet

**Comment by SallyMcGrath** [comment]
## Fundamentals first pass done

https://github.com/CodeYourFuture/Course-Fundamentals
https://github.com/orgs/CodeYourFuture/projects/88

- [x] All G Classroom tech ed assignments are transferred to Github issues
- [x] All new issues have correct labels according to their type e.g. mandatory, etc
- [x] All Github issues are exposed on a Github project board as cards
- [x] All Github cards are labelled according to their week in the module
- [x] Each project board has a **Backlog**, **By priority**, **By Week**, **Done** view

NOT DONE
no solutions branch - Greg might add one later I guess?
not updated the README as it bears thinking about - this is a lot to learn! (On the other hand, this lot will arrive already having deployed 5 sites to Netlify via Github)

**Comment by Dedekind561** [comment]
# Node first pass done:

https://github.com/CodeYourFuture/Module-Node
https://github.com/orgs/CodeYourFuture/projects/85

- [x] All G Classroom tech ed assignments are transferred to Github issues
- [x] All new issues have correct labels according to their type e.g. mandatory, etc
- [x] All Github issues are exposed on a Github project board as cards
- [x] All Github cards are labelled according to their week in the module *note on this
- [x] Each project board has a Backlog, By priority, By Week, Done view
- [x] Move the mandatory projects into the repo
- [ ] Rewrite step by step tutorials as project briefings
- [x] Move the solutions into a branch
- [ ] Deploy the repo to Netlify so disposable branch previews will activate automatically on PR

**Comment by Dedekind561** [comment]
@SallyMcGrath I've set up the Node Module project using [npm workspaces](https://docs.npmjs.com/cli/v9/using-npm/workspaces?v=true) so trainees should only need to install the `express` dependency once from the root of the repo. If they need specific versions for a given sub-dir ( which I'm almost certain they won't ) they can install at the sub-dir level too.

**Comment by Dedekind561** [comment]
# JS1 first pass done:

https://github.com/CodeYourFuture/Module-JS1
https://github.com/orgs/CodeYourFuture/projects/91

- [x] All G Classroom tech ed assignments are transferred to Github issues
- [x] All new issues have correct labels according to their type e.g. mandatory, etc
- [x] All Github issues are exposed on a Github project board as cards
- [x] All Github cards are labelled according to their week in the module *note on this
- [x] Each project board has a Backlog, By priority, By Week, Done view
- [x] Move the mandatory projects into the repo
- [ ] Rewrite step by step tutorials as project briefings
- [x] Move the solutions into a branch
- [ ] Deploy the repo to Netlify so disposable branch previews will activate automatically on PR

**Comment by Dedekind561** [comment]
# JS2 first pass done:

https://github.com/CodeYourFuture/Module-JS1
https://github.com/orgs/CodeYourFuture/projects/91

- [ ] All G Classroom tech ed assignments are transferred to Github issues
- [x] All new issues have correct labels according to their type e.g. mandatory, etc
- [x] All Github issues are exposed on a Github project board as cards
- [ ] All Github cards are labelled according to their week in the module *note on this
- [x] Each project board has a Backlog, By priority, By Week, Done view
- [x] Move the mandatory projects into the repo
- [ ] Rewrite step by step tutorials as project briefings
- [ ] Move the solutions into a branch
- [ ] Deploy the repo to Netlify so disposable branch previews will activate automatically on PR
